#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbASPDemo")]
	public partial class dbDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InserttProduct(tProduct instance);
    partial void UpdatetProduct(tProduct instance);
    partial void DeletetProduct(tProduct instance);
    partial void InserttShoppingCart(tShoppingCart instance);
    partial void UpdatetShoppingCart(tShoppingCart instance);
    partial void DeletetShoppingCart(tShoppingCart instance);
    partial void InserttCustomer(tCustomer instance);
    partial void UpdatetCustomer(tCustomer instance);
    partial void DeletetCustomer(tCustomer instance);
    #endregion
		
		public dbDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbASPDemoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tProduct> tProduct
		{
			get
			{
				return this.GetTable<tProduct>();
			}
		}
		
		public System.Data.Linq.Table<tShoppingCart> tShoppingCart
		{
			get
			{
				return this.GetTable<tShoppingCart>();
			}
		}
		
		public System.Data.Linq.Table<tCustomer> tCustomer
		{
			get
			{
				return this.GetTable<tCustomer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tProduct")]
	public partial class tProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fId;
		
		private string _fName;
		
		private System.Nullable<int> _fQty;
		
		private System.Nullable<decimal> _fCost;
		
		private System.Nullable<decimal> _fPrice;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfIdChanging(int value);
    partial void OnfIdChanged();
    partial void OnfNameChanging(string value);
    partial void OnfNameChanged();
    partial void OnfQtyChanging(System.Nullable<int> value);
    partial void OnfQtyChanged();
    partial void OnfCostChanging(System.Nullable<decimal> value);
    partial void OnfCostChanged();
    partial void OnfPriceChanging(System.Nullable<decimal> value);
    partial void OnfPriceChanged();
    #endregion
		
		public tProduct()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fId
		{
			get
			{
				return this._fId;
			}
			set
			{
				if ((this._fId != value))
				{
					this.OnfIdChanging(value);
					this.SendPropertyChanging();
					this._fId = value;
					this.SendPropertyChanged("fId");
					this.OnfIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fName", DbType="NVarChar(50)")]
		public string fName
		{
			get
			{
				return this._fName;
			}
			set
			{
				if ((this._fName != value))
				{
					this.OnfNameChanging(value);
					this.SendPropertyChanging();
					this._fName = value;
					this.SendPropertyChanged("fName");
					this.OnfNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fQty", DbType="Int")]
		public System.Nullable<int> fQty
		{
			get
			{
				return this._fQty;
			}
			set
			{
				if ((this._fQty != value))
				{
					this.OnfQtyChanging(value);
					this.SendPropertyChanging();
					this._fQty = value;
					this.SendPropertyChanged("fQty");
					this.OnfQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fCost", DbType="Money")]
		public System.Nullable<decimal> fCost
		{
			get
			{
				return this._fCost;
			}
			set
			{
				if ((this._fCost != value))
				{
					this.OnfCostChanging(value);
					this.SendPropertyChanging();
					this._fCost = value;
					this.SendPropertyChanged("fCost");
					this.OnfCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPrice", DbType="Money")]
		public System.Nullable<decimal> fPrice
		{
			get
			{
				return this._fPrice;
			}
			set
			{
				if ((this._fPrice != value))
				{
					this.OnfPriceChanging(value);
					this.SendPropertyChanging();
					this._fPrice = value;
					this.SendPropertyChanged("fPrice");
					this.OnfPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tShoppingCart")]
	public partial class tShoppingCart : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fId;
		
		private string _fDate;
		
		private string _fCustomer;
		
		private string _fProduct;
		
		private System.Nullable<int> _fCount;
		
		private System.Nullable<decimal> _fPrice;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfIdChanging(int value);
    partial void OnfIdChanged();
    partial void OnfDateChanging(string value);
    partial void OnfDateChanged();
    partial void OnfCustomerChanging(string value);
    partial void OnfCustomerChanged();
    partial void OnfProductChanging(string value);
    partial void OnfProductChanged();
    partial void OnfCountChanging(System.Nullable<int> value);
    partial void OnfCountChanged();
    partial void OnfPriceChanging(System.Nullable<decimal> value);
    partial void OnfPriceChanged();
    #endregion
		
		public tShoppingCart()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fId
		{
			get
			{
				return this._fId;
			}
			set
			{
				if ((this._fId != value))
				{
					this.OnfIdChanging(value);
					this.SendPropertyChanging();
					this._fId = value;
					this.SendPropertyChanged("fId");
					this.OnfIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDate", DbType="NVarChar(50)")]
		public string fDate
		{
			get
			{
				return this._fDate;
			}
			set
			{
				if ((this._fDate != value))
				{
					this.OnfDateChanging(value);
					this.SendPropertyChanging();
					this._fDate = value;
					this.SendPropertyChanged("fDate");
					this.OnfDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fCustomer", DbType="NVarChar(50)")]
		public string fCustomer
		{
			get
			{
				return this._fCustomer;
			}
			set
			{
				if ((this._fCustomer != value))
				{
					this.OnfCustomerChanging(value);
					this.SendPropertyChanging();
					this._fCustomer = value;
					this.SendPropertyChanged("fCustomer");
					this.OnfCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fProduct", DbType="NVarChar(50)")]
		public string fProduct
		{
			get
			{
				return this._fProduct;
			}
			set
			{
				if ((this._fProduct != value))
				{
					this.OnfProductChanging(value);
					this.SendPropertyChanging();
					this._fProduct = value;
					this.SendPropertyChanged("fProduct");
					this.OnfProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fCount", DbType="Int")]
		public System.Nullable<int> fCount
		{
			get
			{
				return this._fCount;
			}
			set
			{
				if ((this._fCount != value))
				{
					this.OnfCountChanging(value);
					this.SendPropertyChanging();
					this._fCount = value;
					this.SendPropertyChanged("fCount");
					this.OnfCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPrice", DbType="Money")]
		public System.Nullable<decimal> fPrice
		{
			get
			{
				return this._fPrice;
			}
			set
			{
				if ((this._fPrice != value))
				{
					this.OnfPriceChanging(value);
					this.SendPropertyChanging();
					this._fPrice = value;
					this.SendPropertyChanged("fPrice");
					this.OnfPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tCustomer")]
	public partial class tCustomer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fId;
		
		private string _fName;
		
		private string _fPhone;
		
		private string _fEmail;
		
		private string _fAddress;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfIdChanging(int value);
    partial void OnfIdChanged();
    partial void OnfNameChanging(string value);
    partial void OnfNameChanged();
    partial void OnfPhoneChanging(string value);
    partial void OnfPhoneChanged();
    partial void OnfEmailChanging(string value);
    partial void OnfEmailChanged();
    partial void OnfAddressChanging(string value);
    partial void OnfAddressChanged();
    #endregion
		
		public tCustomer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fId
		{
			get
			{
				return this._fId;
			}
			set
			{
				if ((this._fId != value))
				{
					this.OnfIdChanging(value);
					this.SendPropertyChanging();
					this._fId = value;
					this.SendPropertyChanged("fId");
					this.OnfIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fName", DbType="NVarChar(50)")]
		public string fName
		{
			get
			{
				return this._fName;
			}
			set
			{
				if ((this._fName != value))
				{
					this.OnfNameChanging(value);
					this.SendPropertyChanging();
					this._fName = value;
					this.SendPropertyChanged("fName");
					this.OnfNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fPhone", DbType="NVarChar(50)")]
		public string fPhone
		{
			get
			{
				return this._fPhone;
			}
			set
			{
				if ((this._fPhone != value))
				{
					this.OnfPhoneChanging(value);
					this.SendPropertyChanging();
					this._fPhone = value;
					this.SendPropertyChanged("fPhone");
					this.OnfPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fEmail", DbType="NVarChar(50)")]
		public string fEmail
		{
			get
			{
				return this._fEmail;
			}
			set
			{
				if ((this._fEmail != value))
				{
					this.OnfEmailChanging(value);
					this.SendPropertyChanging();
					this._fEmail = value;
					this.SendPropertyChanged("fEmail");
					this.OnfEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAddress", DbType="NVarChar(50)")]
		public string fAddress
		{
			get
			{
				return this._fAddress;
			}
			set
			{
				if ((this._fAddress != value))
				{
					this.OnfAddressChanging(value);
					this.SendPropertyChanging();
					this._fAddress = value;
					this.SendPropertyChanged("fAddress");
					this.OnfAddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
